# Generated by Django 6.0 on 2025-12-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
